# Generated by Django 5.2.5 on 2025-08-10 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='aia_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('total_images', models.IntegerField(default=0)),
                ('total_icons', models.IntegerField(default=0)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_path', models.CharField(max_length=500)),
                ('extracted_file', models.ImageField(upload_to='extracted_images/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_size', models.IntegerField()),
                ('format', models.CharField(max_length=10)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('quality_rating', models.CharField(blank=True, choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('excellent', 'Excelente')], max_length=10, null=True)),
                ('asset_type', models.CharField(choices=[('image', 'Imagem'), ('icon', 'Ícone'), ('background', 'Fundo'), ('button', 'Botão'), ('other', 'Outro')], default='image', max_length=20)),
                ('resolution_adequate', models.BooleanField(blank=True, null=True)),
                ('aspect_ratio_appropriate', models.BooleanField(blank=True, null=True)),
                ('file_size_optimized', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aia_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='analyzer.aiafile')),
            ],
        ),
        migrations.CreateModel(
            name='UsabilityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_quality_score', models.FloatField(default=0)),
                ('icon_quality_score', models.FloatField(default=0)),
                ('overall_usability_score', models.FloatField(default=0)),
                ('high_quality_images_count', models.IntegerField(default=0)),
                ('low_quality_images_count', models.IntegerField(default=0)),
                ('oversized_images_count', models.IntegerField(default=0)),
                ('undersized_images_count', models.IntegerField(default=0)),
                ('recommendations', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('aia_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='analyzer.aiafile')),
            ],
        ),
    ]
