# Generated by Django 5.2.5 on 2025-08-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='is_material_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='material_icon_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
